version: "3"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on :
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - wordpress_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    environment:
      URL: ${URL}
      ADM_NAME: ${ADM_NAME}
      ADM_PASSWORD: ${ADM_PASSWORD}
      ADM_EMAIL: ${ADM_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      USER_EMAIL: ${USER_EMAIL}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    networks:
      - wordpress_network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wjuneo-f/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wjuneo-f/wordpress